- hosts: testservers
  become: yes
  vars:
    is_some_flag: true
    is_other_flag: false

  tasks:
    - name: update package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: create user john
      tags: users
      ansible.builtin.user:
        name: john
        append: yes

    - name: echo true
      tags: echo
      ansible.builtin.shell: echo "This is true"
      when: is_some_flag

    - name: echo false
      tags: echo
      ansible.builtin.shell: echo "This is false"
      when: not is_other_flag

    - name: install applications
      tags: [app, cowsay]
      ansible.builtin.apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop:
        - git
        - redis-server
        - cowsay

    - name: cowsay
      tags: cowsay
      ansible.builtin.shell: /usr/games/cowsay {{ server_name }}
      register: cowsay_result

    - name: Include nginx playbook
      ansible.builtin.import_playbook: nginx.yaml
