- hosts: testservers
  become: yes
  vars:
    nginx_conf_dist: /etc/nginx/
    nginx_html_dist: /usr/share/nginx/html/
    nginx_port: 8080

  tasks:
    - name: update package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: install git
      tags: app
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: yes

    - name: install nginx
      tags: [app, nginx]
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes

    - name: create user john
      tags: users
      ansible.builtin.user:
        name: john
        groups: unknown
        append: yes

    - name: copy index for nginx
      tags: nginx
      ansible.builtin.copy:
        src: files/index.html
        dest: "{{nginx_html_dist}}/index.html"

    - name: copy nginx config
      tags: nginx
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: "{{nginx_conf_dist}}/nginx.conf"
      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
